version: '3'
services:

  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - "7432:5432"

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_HOST=db
      - DB_NAME=test
      - ADMIN_USERS=postgres,test
      - AUTH_TYPE=plain
    ports:
      - "5432:5432"
    depends_on:
      - db